# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "M_pixel"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John Urban"
description = "basic vector drawing into a pixel graphics format"
categories = ["graphics"]
keywords = ["fortran", "pixel", "draw", "plot", "graphics" ]
homepage = "https://github.com/urbanjost/M_pixel.git"

[build]

# pre-version8 compatibility
[fortran]
implicit-typing = true
implicit-external = true
source-form = "default"

[[executable]]
   name="slices"
   source-dir="app/slices"
   main="pixel_slices.f90"

#[[test]]
#   name="no"
#   source-dir="test/no"
#   main="circle_animated.f90"

[[test]]
name="test_suite_M_pixel"
source-dir="test/same"
main="test_suite_M_pixel.f90"
[test.dependencies]
M_msg = { git = "https://github.com/urbanjost/M_msg.git" }

[[test]]
name="test_suite_M_pixel_slices"
source-dir="test/same"
main="test_suite_M_pixel_slices.f90"
[test.dependencies]
M_msg = { git = "https://github.com/urbanjost/M_msg.git" }
