# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "M_pixel"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John Urban"
description = "basic vector drawing into a pixel graphics format"

#[[test]]
#   name="runTests"
#   source-dir="test"
#   main="test_suite_M_pixel.f90"

[[executable]]
   name="slices"
   source-dir="app/slices"
   main="pixel_slices.f90"
#   [test.dependencies]

#[[test]]
#   source-dir="test/gif/mandelbrot"
#   name="gif"
#   main="mandelbrot.f90"
[[test]]
   source-dir="test/no"
   name="no"
   main="circle_animated.f90"
[[test]]
   source-dir="demos"
   name="arc"
   main="arc.f90"
[[test]]
   source-dir="demos"
   name="centertext"
   main="centertext.f90"
[[test]]
   source-dir="demos"
   name="circle"
   main="circle.f90"
[[test]]
   source-dir="demos"
   name="circleprecision"
   main="circleprecision.f90"
#[[test]]
#   source-dir="demos"
#   name="clear"
#   main="clear.f90"
#[[test]]
#   source-dir="demos"
#   name="closepoly"
#   main="closepoly.f90"
[[test]]
   source-dir="demos"
   name="color"
   main="color.f90"
[[test]]
   source-dir="demos"
   name="draw2"
   main="draw2.f90"
[[test]]
   source-dir="demos"
   name="drawchar"
   main="drawchar.f90"
[[test]]
   source-dir="demos"
   name="drawstr"
   main="drawstr.f90"
[[test]]
   source-dir="demos"
   name="font"
   main="font.f90"
#[[test]]
#   source-dir="demos"
#   name="getdisplaysize"
#   main="getdisplaysize.f90"
[[test]]
   source-dir="demos"
   name="getgp2"
   main="getgp2.f90"
#[[test]]
#   source-dir="demos"
#   name="getviewport"
#   main="getviewport.f90"
[[test]]
   source-dir="demos"
   name="hershey"
   main="hershey.f90"
#[[test]]
#   source-dir="demos"
#   name="justfy"
#   main="justfy.f90"
#[[test]]
#   source-dir="demos"
#   name="line"
#   main="line.f90"
[[test]]
   source-dir="demos"
   name="linewidth"
   main="linewidth.f90"
[[test]]
   source-dir="demos"
   name="makepoly"
   main="makepoly.f90"
[[test]]
   source-dir="demos"
   name="mapcolor"
   main="mapcolor.f90"
[[test]]
   source-dir="demos"
   name="move2"
   main="move2.f90"
[[test]]
   source-dir="demos"
   name="M_pixel"
   main="M_pixel.f90"
#[[test]]
#   source-dir="demos"
#   name="ortho2"
#   main="ortho2.f90"
#[[test]]
#   source-dir="demos"
#   name="page"
#   main="page.f90"
[[test]]
   source-dir="demos"
   name="point2"
   main="point2.f90"
[[test]]
   source-dir="demos"
   name="poly2"
   main="poly2.f90"
[[test]]
   source-dir="demos"
   name="polyline2"
   main="polyline2.f90"
[[test]]
   source-dir="demos"
   name="prefsize"
   main="prefsize.f90"
[[test]]
   source-dir="demos"
   name="print_ascii"
   main="print_ascii.f90"
[[test]]
   source-dir="demos"
   name="print_ppm"
   main="print_ppm.f90"
[[test]]
   source-dir="demos"
   name="rdraw2"
   main="rdraw2.f90"
[[test]]
   source-dir="demos"
   name="rect"
   main="rect.f90"
[[test]]
   source-dir="demos"
   name="rmove2"
   main="rmove2.f90"
[[test]]
   source-dir="demos"
   name="state"
   main="state.f90"
[[test]]
   source-dir="demos"
   name="strlength"
   main="strlength.f90"
[[test]]
   source-dir="demos"
   name="textang"
   main="textang.f90"
[[test]]
   source-dir="demos"
   name="textsize"
   main="textsize.f90"
[[test]]
   source-dir="demos"
   name="vexit"
   main="vexit.f90"
#[[test]]
#   source-dir="demos"
#   name="viewport"
#   main="viewport.f90"
[[test]]
   source-dir="demos"
   name="vinit"
   main="vinit.f90"
#[[test]]
#   source-dir="demos"
#   name="xcentertext"
#   main="xcentertext.f90"
#[[test]]
#   source-dir="demos"
#   name="ycentertext"
#   main="ycentertext.f90"
[[test]]
   source-dir="demos"
   name="readgif"
   main="readgif.f90"
[[test]]
   source-dir="demos"
   name="write_animated_gif"
   main="write_animated_gif.f90"
#[[test]]
#   source-dir="demos"
#   name="write_animated_gif.3m_writegif_animated"
#   main="write_animated_gif.3m_writegif_animated.f90"
[[test]]
   source-dir="demos"
   name="writegif"
   main="writegif.f90"
[[test]]
   source-dir="demos"
   name="closest_color_name"
   main="closest_color_name.f90"
[[test]]
   source-dir="demos"
   name="color_name2rgb"
   main="color_name2rgb.f90"
[[test]]
   source-dir="demos"
   name="hue"
   main="hue.f90"
[[test]]
   source-dir="demos"
   name="d2r"
   main="d2r.f90"
[[test]]
   source-dir="demos"
   name="demos/polar_to_cartesian"
   main="polar_to_cartesian.f90"
#[[test]]
#   source-dir="test/gif"
#   name="gif"
#   main="circle_illusion.f90"
